### ISSUE TITLE
Can you use IAM roles ?

### ISSUE THREAD

**Issue by andreijs** [MikaAK/s3-plugin-webpack#31]
Just wondering had a look at the code doesn't seem it has the capability

**Comment by MikaAK** [comment]
I don't really understand, your welcome to create a PR with the functionality and I'll merge it in

**Comment by MikaAK** [comment]
Closing as I don't think this is going anywhere. Feel free to reopen if you think i should relook at this

**Comment by snario** [comment]
@MikaAK Basically it would be nice if you could just remove the restriction

```
ERROR in S3Plugin: Must provide accessKeyId, secretAccessKey
```

If you don't provide those args and the request is sent to AWS without them, then the role of the instance running this command in AWS will be used.

**Comment by MikaAK** [comment]
@snario I'm not familiar with using IAM for authentication. Can you explain how it would be able to upload anything without providing some sort of identification?

**Comment by snario** [comment]
On AWS you can assign a role to an EC2 instance and attach a policy to allow S3 bucket uploads from instances with that role. The AWS API knows how to handle requests coming from instances with roles and as such will function as expected without any access key or secret key passed in (the keys are temporary and stored in instance metadata).
Examplehttp://parthicloud.com/how-to-access-s3-bucket-from-application-on-amazon-ec2-without-access-credentials/
All this project needs to do is not throw an error.
Actually I think there is a bug in this project because the files actually upload fine despite credentials being missing. It prints that error, but then proceeds to upload the files.

Sent from my iPhone




On Sat, May 14, 2016 at 11:24 AM -0700, "Mika Kalathil" <notifications@github.com> wrote:












@snario I'm not familiar with using IAM for authentication. Can you explain how it would be able to upload anything without providing some sort of identification?

**Comment by MikaAK** [comment]
Funny enough there's no logic to quit after erroring. Is there any way to check for credentials when using this form of authentication? I would still like to be able to inform people for specific errors.

**Comment by snario** [comment]
I would just throw a warning instead of an error.

If the user tries to upload without credentials then AWS will throw an error which should be descriptive enough to know what's wrong.

**Comment by MikaAK** [comment]
Sure I'll push that up later today

**Comment by MikaAK** [comment]
Having a weird issue where errors don't emit after pushing them to webpack once the upload fails if there's no key. Till I can figure this one out I'm stuck with emitting errors :( hopefully I can find a fix soon!
