### ISSUE TITLE
Version 0.9.1 is missing in registry.npmjs.org

### ISSUE THREAD

**Issue by egut** [MikaAK/s3-plugin-webpack#57]
Hi, and thanks for submitting a fix for cache invalidation but npm can't find the new version :(

I did look at https://www.npmjs.com/package/webpack-s3-plugin and the 0.9.1 is visible, you have published 0.9.1 in this repo but in https://registry.npmjs.org/webpack-s3-plugin it still say 0.9.0 is the latest (even tho 0.9.1 has a time in the json file).

So I'm guessing that the publishing of 0.9.1 failed some how so could you please try to republish the 0.9.1 version?

/BR
   Erik

**Comment by bgannonPL** [comment]
Second this -- for some reason the `progress` implementation errors out at a certain point in my webpack build; I can't disable it because the disable option isn't in 0.9.0. (I know, I could/should file a bug report about the error, but our webpack build is very complex and we have a lot to do ... switching it off would be ideal for now)

**Comment by MikaAK** [comment]
I don't know why but I can't remove 0.9.1, published under 0.9.2
